### ISSUE TITLE
Feature: `-s|--silent` mode with no console output.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/trace-pkg#12]

**Comment by Burnett2k** [comment]
Mind if I take a look at this one? If so, is it correct that if silent mode is set you don't want to see any console output at all? Not even errors?

**Comment by ryan-roemer** [comment]
Sure! It would be no console/warn/error output and just throw the error directly.

The “—report” flag still needs output

**Comment by ryan-roemer** [comment]
And implementation wise, I'd refactor https://github.com/FormidableLabs/trace-pkg/blob/main/lib/log.js to take an `enabled` flag that is inferred from options to the CLI or something and make getters that return functions which either do appropriate logging or are a noop... Just one potential way!

**Comment by Burnett2k** [comment]
Makes sense. Thanks for the info. I hacked something together quickly yesterday that works, but I will spend a bit more time to get it nice and clean

**Comment by Burnett2k** [comment]
Closing this issue now that silent mode made it into a release
